// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6J9nv8DRtdvmYlyW4DLUpBcCmNulv7HM',
    appId: '1:362390934074:android:eabfed4bac7e84a78f5b03',
    messagingSenderId: '362390934074',
    projectId: 'riskassessment-fe4e0',
    databaseURL: 'https://riskassessment-fe4e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riskassessment-fe4e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqybcWzG_pGZfjzA3YfEeEq4Ui3aN43Tw',
    appId: '1:362390934074:ios:5c7a0e718432e04a8f5b03',
    messagingSenderId: '362390934074',
    projectId: 'riskassessment-fe4e0',
    databaseURL: 'https://riskassessment-fe4e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riskassessment-fe4e0.appspot.com',
    iosClientId: '362390934074-17h0kot11omkf8ilkdnb9v1k46abahbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.riskassessment',
  );
}
